version: '3.7'

networks:
    services:
      ipam:
        config:
          - subnet: 10.0.0.0/8

services:
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
           - "2181:2181"
    kafka:
        image: wurstmeister/kafka
        ports:
            - "9092"
        links:
            - zookeeper
        environment:
            KAFKA_ADVERTISED_HOST_NAME: 10.0.0.10
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: "topic1:1:3"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock